# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI - Tests

#Quando deve executar?
on:
  push:
    branches: [ main ]

#cron schedule - definir horários, dia

 workflow_dispatch: 

jobs:
  build:
  #qual maquina vamos executar?
    runs-on: ubuntu-latest

    steps:
  # Serve pra baixar o nosso código
    - uses: actions/checkout@v2
    
  # Serve para configurar o node
  - name: Use Node.js
    uses: actions/setup-node@v2
    with:
      node-version: 14.x
        
  # Instalar dependências
    - run: npm install
    
  # Executar os testes
    - run: npx cypress run

  # Merge do relatório
    - run: npm run report:merge

  # Gerar o relatório
    - run: npm run report:generate
    
  #upload do artefado
  - name: Upload a Build Artifact
    uses: actions/upload-artifact@v2.2.3
    with:
      path: mochawesome-report
